//
//  UIColor+HBZAdditions.h
//
//  Generated by Zeplin on 5/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (HBZAdditions)

+ (UIColor *)hbz_c13Color;
+ (UIColor *)hbz_c12Color;
+ (UIColor *)hbz_c11Color;
+ (UIColor *)hbz_c10Color;
+ (UIColor *)hbz_c9Color;
+ (UIColor *)hbz_c8Color;
+ (UIColor *)hbz_c7Color;
+ (UIColor *)hbz_c6Color;
+ (UIColor *)hbz_c5Color;
+ (UIColor *)hbz_c4Color;
+ (UIColor *)hbz_c3Color;
+ (UIColor *)hbz_c2Color;
+ (UIColor *)hbz_c1Color;

@end
