//
//  UIColor+HBZAdditions.m
//
//  Generated by Zeplin on 5/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+HBZAdditions.h"

@implementation UIColor (HBZAdditions)

+ (UIColor *)hbz_c13Color {
	return [UIColor colorWithRed:101.0f / 255.0f green:208.0f / 255.0f blue:49.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c12Color {
	return [UIColor colorWithRed:247.0f / 255.0f green:82.0f / 255.0f blue:10.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c11Color {
	return [UIColor colorWithRed:255.0f / 255.0f green:156.0f / 255.0f blue:0.0 alpha:1.0f];
}

+ (UIColor *)hbz_c10Color {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c9Color {
	return [UIColor colorWithRed:248.0f / 255.0f green:250.0f / 255.0f blue:251.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c8Color {
	return [UIColor colorWithWhite:228.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c7Color {
	return [UIColor colorWithWhite:219.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c6Color {
	return [UIColor colorWithWhite:192.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c5Color {
	return [UIColor colorWithWhite:153.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c4Color {
	return [UIColor colorWithWhite:102.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c3Color {
	return [UIColor colorWithWhite:34.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c2Color {
	return [UIColor colorWithRed:112.0f / 255.0f green:159.0f / 255.0f blue:67.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)hbz_c1Color {
	return [UIColor colorWithRed:147.0f / 255.0f green:193.0f / 255.0f blue:7.0f / 255.0f alpha:1.0f];
}

@end
