//
//  UIFont+HBZAdditions.m
//
//  Generated by Zeplin on 5/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+HBZAdditions.h"

@implementation UIFont (HBZAdditions)

+ (UIFont *)hbz_h1Font {
	return [UIFont systemFontOfSize:19.0f];
}

+ (UIFont *)hbz_h2Font {
	return [UIFont systemFontOfSize:18.0f];
}

+ (UIFont *)hbz_h3Font {
	return [UIFont systemFontOfSize:17.0f];
}

+ (UIFont *)hbz_h4Font {
	return [UIFont systemFontOfSize:16.0f];
}

+ (UIFont *)hbz_h5Font {
	return [UIFont systemFontOfSize:15.0f];
}

+ (UIFont *)hbz_h6Font {
	return [UIFont systemFontOfSize:13.0f];
}

+ (UIFont *)hbz_h7Font {
	return [UIFont systemFontOfSize:12.0f];
}

+ (UIFont *)hbz_h8Font {
	return [UIFont systemFontOfSize:10.0f];
}

@end
