//
//  UIFont+HBZAdditions.h
//
//  Generated by Zeplin on 5/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (HBZAdditions)

+ (UIFont *)hbz_h1Font;
+ (UIFont *)hbz_h2Font;
+ (UIFont *)hbz_h3Font;
+ (UIFont *)hbz_h4Font;
+ (UIFont *)hbz_h5Font;
+ (UIFont *)hbz_h6Font;
+ (UIFont *)hbz_h7Font;
+ (UIFont *)hbz_h8Font;

@end
